modLoader = "javafml"
loaderVersion = "${neo_loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/Khajiitos/WorldPlayTime/issues"

[[mods]]
modId = "flexyversions"
version = "${version}"
logoFile="icon.png"
displayName = "World Play Time"
authors = "Khajiitos"
displayURL="https://github.com/Khajiitos/WorldPlayTime"
description = '''Displays the world's play time in the world selection menu.'''
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config="flexyversions.mixins.json"

[[dependencies.flexyversions]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.flexyversions]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.3]"
ordering = "NONE"
side = "BOTH"

