modLoader = "javafml"
loaderVersion = "${neo_loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/Khajiitos/ChestedCompanions/issues"

[[mods]]
modId = "chestedcompanions"
version = "${version}"
logoFile = "icon.png"
displayName = "Chested Companions"
authors = "Khajiitos"
displayURL = "https://github.com/Khajiitos/ChestedCompanions"
description = '''Equip chests on your fluffy friends!'''
updateJSONURL = "https://updates.khajiitos.fun/chested-companions/updates-neoforge.json"
displayTest = "MATCH_VERSION"

[[mixins]]
config="chestedcompanions.mixins.json"

[[dependencies.chestedcompanions]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.chestedcompanions]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

